version: '3.3'

services:

    nginx:
        restart: always
        command: /bin/bash -c "sleep 120s && envsubst '$$NGINX_HOST $$NGINX_PORT $$USER_USER $$USER1_USER $$USER2_USER $$USER3_USER' < /etc/nginx/conf.d/nginx.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

    postgres:
        restart: always

    cassandra:
        restart: always

    cassandra-client:

    cassandra-web:
        restart: always

    ignite:
        restart: always

    adminer:
        restart: always

    airflow:
        restart: always
        environment:
            LOAD_EX: n

    mlflow:
        restart: always

    zookeeper:
        restart: always

    kafka:
        restart: always
        environment:
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://yamlops.uk.to:9093


    kafdrop:
        restart: always

    rest-prediction:
        restart: always
        command: /bin/bash -c "sleep 40s && python ./rest-prediction.py --run-id 44463a7b9f044b5ea6aaddb32bf0f4df --kafka-topic bracelet-feed"

    spark-master:
        restart: always

    spark-worker-1:
        restart: always

    jupyter:
        restart: always

    jupyter1:
        restart: always

    jupyter2:
        restart: always

    jupyter3:
        restart: always
